name: sigurdur.com
favicon: null
layout_spectrum: 0.7110329137649387
typography_spectrum: 0.9104466536082327
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7810534101445228
  lightness: 0.4103857520967722
  saturation: 0.18530019815079868
  rhythmicContrast: 0.872470977017656
purpose: []
